trigger:
- main
resources:
- repo: self
pool:
  name: data_engineering_apps
variables:
- group: ACR-SP-credentials
stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build and push an image to container registry
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: airflow
        dockerfile: $(Build.SourcesDirectory)/Dockerfile
        containerRegistry: f5793cca-c4be-4f01-a005-4a6be114a4a9
        tags: $(Build.BuildId)
- stage: Deploy
  jobs:
  - job: PullImage
    steps:
    - script: |
        image_name=dataEngineeringApps.azurecr.io/airflow:$(Build.BuildId)

        # Set the Azure Pipeline variables as environment variables. They will be used in the docker-compose.yaml file.
        export CONTAINER_REGISTRY=dataEngineeringApps.azurecr.io
        export IMAGE_REPOSITORY=airflow
        export IMAGE_TAG=$(Build.BuildId)

        # Below arguments SP_ID and SP_PASSWORD will be taken from the DevOps Library Variable group.
        echo "Login to Docker using service principal credentials"
        docker login dataEngineeringApps.azurecr.io -u $(SP_ID) -p $(SP_PASSWORD)

        echo "Pulling the Docker image"
        docker pull $image_name

        echo "Running the Docker container"
        docker compose -f docker-compose.yaml up -d
